[gh-478] Fix branch build

diff --git a/.github/workflows/roslyn-branches.yml b/.github/workflows/roslyn-branches.yml
--- a/.github/workflows/roslyn-branches.yml
+++ b/.github/workflows/roslyn-branches.yml
@@ -18,7 +18,8 @@ jobs:
       run: |
         $ErrorActionPreference = 'Stop'
         Install-Module -Name Az -RequiredVersion 2.6.0 -Force -AllowClobber
-        Uninstall-AzureRM
+      shell: |
+        pwsh -noninteractive -command "try {{ $ErrorActionPreference='Stop'; . '{0}' }} catch {{ Write-Error ""FAILED: $_""; throw; }} if ((Test-Path -LiteralPath variable:\LASTEXITCODE)) {{ exit $LASTEXITCODE }}"
     - name: Update-All
       env:
         SHARPLAB_TELEMETRY_KEY: ${{secrets.AzureBranchTelemetryKey}}
@@ -26,4 +27,6 @@ jobs:
         SL_BUILD_AZURE_APP_ID:  ${{secrets.AzureAppID}}
         SL_BUILD_AZURE_SECRET:  ${{secrets.AzureSecret}}
       run: |
-        powershell .\#scripts\roslyn-branches\Update-All.ps1 -Azure
+        .\#scripts\roslyn-branches\Update-All.ps1 -Azure
+      shell: |
+        pwsh -noninteractive -command "try {{ $ErrorActionPreference='Stop'; . '{0}' }} catch {{ Write-Error ""FAILED: $_""; throw; }} if ((Test-Path -LiteralPath variable:\LASTEXITCODE)) {{ exit $LASTEXITCODE }}"
